# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # First job declared is for building things..
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Building things..."
      - persist_to_workspace:
          root: .
          paths:
            - .
  # Second job declared is for launching unit tests with Jest
  unit-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: |
            mkdir -p ./test-results/
            npm run test:ci
      - store_test_results:
          path: ./test-results/

  test-node:
    # Install node dependencies and run tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  deploy_dev:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: echo "Deploying to development environment..."

  deploy_tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: echo "Deploying to tests environment..."

  deploy_prod:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: echo "Deploying to production environment..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build

      - unit-tests:
          requires:
            - build

      - test-node:
          requires:
            - build

      - deploy_dev:
          requires:
            - unit-tests
          filters:
            branches:
              only:
                - workspace_pc_dev

      - deploy_tests:
          requires:
            - unit-tests
          filters:
            branches:
              only:
                - workspace_pc_tests

      - deploy_prod:
          requires:
            - unit-tests
          filters:
            branches:
              only:
                - workspace_pc
